# Generated by Django 3.2 on 2021-04-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on', models.TimeField()),
                ('time_off', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_not_water', models.BooleanField(default=False)),
                ('has_not_food', models.BooleanField(default=False)),
                ('is_heater_on', models.BooleanField(default=False)),
                ('is_motor_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level', models.PositiveSmallIntegerField(default=0)),
                ('temperature', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_filled', models.DateTimeField()),
                ('finishing_time', models.FloatField()),
            ],
        ),
    ]
